"""create_users_table

Revision ID: d5245f5576f8
Revises: 0007_create_skills
Create Date: 2026-07-20 14:49:58.172972
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd5245f5576f8'
down_revision = '0007_create_skills'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名(唯一)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱(唯一)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('full_name', sa.String(length=128), nullable=True, comment='全名'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='头像URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='用户状态'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='扩展元数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='软删除标记: false 有效 / true 已删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间, 空表示未删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('permission_rules', 'behavior',
               existing_type=sa.VARCHAR(length=16),
               comment='判定行为: allow 放行 / ask 需审批 / deny 拒绝',
               existing_comment='判定行为: allow / ask / deny',
               existing_nullable=False)
    op.alter_column('permission_rules', 'matcher',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='细化匹配条件(预留, 空表示按 tool_name 全匹配)',
               existing_comment='细化匹配条件(预留)',
               existing_nullable=True)
    op.alter_column('permission_rules', 'source',
               existing_type=sa.VARCHAR(length=16),
               comment='规则来源: user 设置页配置 / always_allow 审批时始终允许落库',
               existing_comment='规则来源: user / always_allow',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('permission_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('permission_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('session_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('session_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='最后活跃时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'id',
               existing_type=sa.INTEGER(),
               comment='skillID',
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=64),
               comment='skill名称;覆盖更新与工具路由的键',
               existing_comment='skill名称',
               existing_nullable=False)
    op.alter_column('skills', 'description',
               existing_type=sa.TEXT(),
               comment='skill描述(注入系统提示供发现)',
               existing_comment='skill描述',
               existing_nullable=False)
    op.alter_column('skills', 'frontmatter',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='解析后的完整frontmatter快照',
               existing_comment='解析后的完整frontmatter',
               existing_nullable=False)
    op.alter_column('skills', 'version',
               existing_type=sa.VARCHAR(length=32),
               comment='frontmatter声明的版本号',
               existing_comment='版本号',
               existing_nullable=True)
    op.alter_column('skills', 'skill_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='上传zip包的哈希,幂等上传判重',
               existing_comment='上传zip包的哈希',
               existing_nullable=True)
    op.alter_column('skills', 'scope',
               existing_type=sa.VARCHAR(length=16),
               comment='作用域:预留隔离维度,本期恒为global',
               existing_comment='作用域',
               existing_nullable=False,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='软删除标记: false 有效 / true 已删除',
               existing_comment='软删除标记',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('skills', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='软删除时间, 空表示未删除',
               existing_comment='软删除时间',
               existing_nullable=True)
    op.create_table_comment(
        'skills',
        'web端上传的skill',
        existing_comment='skills',
        schema=None
    )
    op.alter_column('subagent_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='开始时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('team_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='开始时间',
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool_calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='开始时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('team_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('subagent_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='开始时间',
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'skills',
        'skills',
        existing_comment='web端上传的skill',
        schema=None
    )
    op.alter_column('skills', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='软删除时间',
               existing_comment='软删除时间, 空表示未删除',
               existing_nullable=True)
    op.alter_column('skills', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='软删除标记',
               existing_comment='软删除标记: false 有效 / true 已删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'scope',
               existing_type=sa.VARCHAR(length=16),
               comment='作用域',
               existing_comment='作用域:预留隔离维度,本期恒为global',
               existing_nullable=False,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('skills', 'skill_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='上传zip包的哈希',
               existing_comment='上传zip包的哈希,幂等上传判重',
               existing_nullable=True)
    op.alter_column('skills', 'version',
               existing_type=sa.VARCHAR(length=32),
               comment='版本号',
               existing_comment='frontmatter声明的版本号',
               existing_nullable=True)
    op.alter_column('skills', 'frontmatter',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='解析后的完整frontmatter',
               existing_comment='解析后的完整frontmatter快照',
               existing_nullable=False)
    op.alter_column('skills', 'description',
               existing_type=sa.TEXT(),
               comment='skill描述',
               existing_comment='skill描述(注入系统提示供发现)',
               existing_nullable=False)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=64),
               comment='skill名称',
               existing_comment='skill名称;覆盖更新与工具路由的键',
               existing_nullable=False)
    op.alter_column('skills', 'id',
               existing_type=sa.INTEGER(),
               comment='ID',
               existing_comment='skillID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='最后活跃时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('session_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('session_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('permission_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('permission_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('permission_rules', 'source',
               existing_type=sa.VARCHAR(length=16),
               comment='规则来源: user / always_allow',
               existing_comment='规则来源: user 设置页配置 / always_allow 审批时始终允许落库',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('permission_rules', 'matcher',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='细化匹配条件(预留)',
               existing_comment='细化匹配条件(预留, 空表示按 tool_name 全匹配)',
               existing_nullable=True)
    op.alter_column('permission_rules', 'behavior',
               existing_type=sa.VARCHAR(length=16),
               comment='判定行为: allow / ask / deny',
               existing_comment='判定行为: allow 放行 / ask 需审批 / deny 拒绝',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
